import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggle from "@/components/ThemeToggle";
import FooterPadding from "@/components/FooterPadding";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: [
    "OK9981",
    "新闻",
    "资讯",
    "新闻中心",
    "每日资讯",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
        style={{ display: "flex", minHeight: "100vh", flexDirection: "column" }}
      >
        {/* 固定在右上角的主题开关 */}
        <div style={{ position: "fixed", top: 10, right: 12, zIndex: 60 }}>
          <ThemeToggle />
        </div>
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-K4ZX54PHWM" strategy="afterInteractive" />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);} 
            gtag('js', new Date());
            gtag('config', 'G-K4ZX54PHWM');
          `}
        </Script>
        <header style={{
          position: "sticky",
          top: 0,
          backdropFilter: "saturate(180%) blur(6px)",
          background: "color-mix(in oklab, var(--background) 85%, transparent)",
          borderBottom: "1px solid var(--border)",
          zIndex: 50,
        }}>
          <div className="site-container" style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0.8rem 0", paddingRight: "84px" }}>
            <a href="/" style={{ fontWeight: 700, fontSize: "1.05rem", color: "var(--foreground)" }}>每日资讯简报</a>
            <nav style={{ display: "flex", gap: "1rem", alignItems: "center" }}>
              <a href="/" aria-label="首页">首页</a>
              <a href="/news/" aria-label="新闻">新闻</a>
              <a href="/search" aria-label="搜索">搜索</a>
              <a href="/deals/" aria-label="羊毛">羊毛🐑</a>
              {/* ThemeToggle 移除，不跟随链接 */}
            </nav>
          </div>
        </header>
        {children}
        <footer id="site-footer" style={{ position: "fixed", left: 0, right: 0, bottom: 0, borderTop: "1px solid var(--border)", background: "var(--background)", zIndex: 40 }}>
          <div className="site-container" style={{ padding: "1.2rem 0", display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: "0.9rem", color: "var(--muted)" }}>
            <span>© {new Date().getFullYear()} OK9981</span>
            <span>由 Next.js 与 Vercel 驱动</span>
          </div>
        </footer>
        {/* 动态为 body 留出与 footer 等高的空间，避免遮挡 */}
        <FooterPadding />
      </body>
    </html>
  );
}
